---
# file: roles/common/tasks/main.yml

# specify the packages and the packager to use
# see the vars folder for a complete list
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: upgrade all packages
  action: "{{ ansible_pkg_mgr }} pkg=* state=latest"
  when: ansible_distribution != "OpenWrt"

- name: installing default packages
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest"
  with_items: packages
  when: ansible_distribution != "OpenWrt"

- name: installing default packages on an openwrt system
  opkg: name={{ item }} state=present update_cache=true
  with_items: packages
  when: ansible_distribution == "OpenWrt"

- name: disable selinux for now
  selinux: state=disabled
  when: ansible_distribution != "OpenWrt"
