---
# file: roles/common/tasks/main.yml

# specify the packages and the packager to use
# see the vars folder for a complete list
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure yum or dnf repository
  copy: src="{{ ansible_os_family }}_{{ item }}" dest="{{ RedHat_repodest }}/{{ item }}" owner=root group=root mode=0644
  with_items: "{{ ansible_os_family }}_repolist"
  when: item is defined
  tags: repo

- name: upgrade all packages
  action: "{{ ansible_pkg_mgr }} pkg=* state=latest"
  when: ansible_distribution != "OpenWrt" and ansible_os_family != 'Debian'

- name: installing default packages
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest"
  with_items: packages
  when: ansible_distribution != "OpenWrt"

- name: installing default packages on an openwrt system
  opkg: name={{ item }} state=present update_cache=true
  with_items: packages
  when: ansible_distribution == "OpenWrt"

# - name: disable selinux for now
#   selinux: state=disabled
#   when: ansible_distribution != "OpenWrt" and ansible_os_family != 'Debian'

- name: adding mounts to fstab
  mount:
    src: "{{ item.src }}"
    name: "{{ item.name }}"
    fstype: "{{ item.fstype }}"
    state: "{{ item.state|default('mounted') }}"
    opts: "{{ item.opts }}"
    passno: "{{ item.passno|default('2') }}"
    dump: "{{ item.dump|default('1') }}"
  with_items: mounts
  when: mounts is defined

- name: adjust mountpoints group ownership
  file:
    path: "{{ item.name }}"
    group: "{{ item.group}}"
    state: directory
  with_items: mounts
  when: mounts is defined
